routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['verify' => true]);

Route::resource('store', 'Stores\StoreController', ['except' => [
    'index'
]]);

Route::prefix('{store}')->group(function() {
    Route::get('/', 'Stores\StoreController@index')->name('store.index');

    Route::resource('item', 'Items\ItemController', ['except' => [
        'index', 'create', 'edit'
    ]]);
});

Route::namespace('Users')->prefix('/user')->group(function() {
    Route::get('/profile', 'ProfileController@show')->name('user.profile');
    Route::patch('/profile/update', 'ProfileController@update')->name('user.profile.update');
    Route::post('/profile/avatar/update', 'ProfileController@avatar')->name('user.profile.avatar');

    Route::resource('/address', 'AddressController', ['except' => [
        'index', 'create', 'show'
    ]]);

    Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
    Route::post('/wishlist/{item}', 'WishlistController@update')->name('wishlist.update');
});

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Models\Users\User;
use App\Models\Items\Item;

class Store extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'domain';
    }

    public function getImage() : string
    {
        $image = $this->image()->first();

        if ($image) {
            return '/images/store/' . $image->path;
        }

        return str_limit($this->name, 1, '');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function items()
    {
        return $this->hasMany(Item::class);
    }

    public function image()
    {
        return $this->morphMany(Image::class, 'imageable');
    }
}

app/Http/Controllers/Stores/StoreController.php
<?php

namespace App\Http\Controllers\Stores;

use App\Http\Controllers\Controller;

use App\Models\Store;
use App\Models\Purchases\PurchaseType;
use App\Models\Items\ItemCategory;

class StoreController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => 'index']);
        $this->middleware('seller', ['only' => 'create']);
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index(Store $store)
    {
        $items = $store->items()->latest()->get();
        $purchaseTypes = PurchaseType::all();
        $itemCategories = ItemCategory::all();

        return view('store.index', compact('store', 'items', 'purchaseTypes', 'itemCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('store.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     */
    public function store()
    {
        $store = auth()->user()->store()->create([
            'name' => request()->name,
            'domain' => str_slug(request()->name),
            'location' => request()->location,
            'city' => request()->city,
            'description' => request()->description
        ]);

        auth()->user()->assignRole('seller');

        return redirect()->route('store.index', $store);
    }

    /**
     * Display the specified resource.
     *
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     */
    public function edit()
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     */
    public function update()
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy()
    {
        //
    }
}

resources/views/store/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bioresc</title>

    <link rel="icon" href="{{ asset('images/component/logo1.png') }}">

    @include('partials.style')
</head>

<body>
    @include('components.header')

    <div class="row min-h-fullscreen center-vh p-20 m-0">
        <div class="col-12">
            <div class="card card-shadowed px-50 py-30 w-400px mx-auto" style="max-width: 100%">
                <h5>Buat Toko Anda!</h5>
                <br>

                <form class="form-type-material" method="POST" action="{{ route('store.store') }}">
                    @csrf

                    <div class="form-group">
                        <label>Nama Toko</label>
                        <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}"
                            type="text" required>

                        @if ($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('name') }}</strong>
                        </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Kota</label>
                        <input class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city') }}"
                            type="text" required>

                        @if ($errors->has('city'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('city') }}</strong>
                        </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Alamat</label>
                        <input class="form-control{{ $errors->has('location') ? ' is-invalid' : '' }}" name="location"
                            type="text" required>

                        @if ($errors->has('location'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('location') }}</strong>
                        </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>De]skripsi</label>
                        <textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" required></textarea>

                        @if ($errors->has('description'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('description') }}</strong>
                        </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <button class="btn btn-bold btn-block btn-primary" type="submit">Buat Toko</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @include('partials.script')
</body>

</html>

resources/views/store/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bioresc</title>

    <link rel="icon" href="{{ asset('images/component/logo1.png') }}">

    @include('partials.style')
</head>

<body data-provide="pace">
    @include('components.header')

    <div class="p-100">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="d-inline">
                            @if (strlen($store->getImage()) > 1)
                            <img class="avatar avatar-xl" src="{{ $store->getImage() }}">
                            @else
                            <span class="avatar avatar-xl bg-dark fs-25">{{ $store->getImage() }}</span>
                            @endif
                        </div>

                        <h5 class="ml-2 mb-1 d-inline">
                            <a class="hover-primary" href="{{ route('store.index', $store) }}">
                                {{ $store->name }}
                            </a>
                        </h5>

                        <div class="mt-3">
                            <b>Lokasi</b><br>
                            <i class="ti-location-pin"></i>
                            {{ $store->location }}, <b>{{ $store->city }}</b>
                        </div>

                        <div><b>Deskripsi</b><br>{{ $store->description }}</div>
                    </div>

                    @if (auth()->user() && auth()->user()->isOwner($store->user->id))
                    <div class="col-md-6">
                        <button class="btn btn-primary float-md-right" data-target="#modal-add-item" data-toggle="modal"><i
                                class="ti-import"></i> Tambah Barang</button>

                        <div class="modal fade" id="modal-add-item" tabindex="-1" aria-hidden="true" style="display: none;">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title"><i class="ti-import"></i> Tambah Barang</h5>
                                        <button type="button" class="close" data-dismiss="modal">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <form action="{{ route('item.store', $store) }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label>Nama Barang</label>
                                                <input name="name" class="form-control" type="text" value="" required>
                                            </div>
                                            <div class="form-group">
                                                <label>Harga</label>
                                                <input name="price" class="form-control" type="number" min="0" value=""
                                                    required>
                                            </div>
                                            <div class="form-group">
                                                <label>Tipe Satuan</label>
                                                <input name="unit_type" class="form-control" type="text" value=""
                                                    required>
                                            </div>
                                            <div class="form-group">
                                                <label>Status Stok</label>
                                                <select name="stock_status" class="form-control">
                                                    <option value="0">Habis</option>
                                                    <option value="1">Tersedia</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label>Deskripsi</label>
                                                <textarea name="description" class="form-control" required></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label>Foto</label>
                                                <input name="images[]" class="form-control-file" type="file" value=""
                                                    multiple required>
                                            </div>
                                            <div class="form-group">
                                                    <label>Kategori</label>
                                                    @foreach ($itemCategories as $category)
                                                    <div class="checkbox">
                                                        <input type="checkbox" name="item_categories[]" value="{{ $category->id }}"> {{ $category->name }}
                                                    </div>
                                                    @endforeach
                                                </div>
                                            <div class="form-group">
                                                <label>Tipe Pembayaran</label>
                                                @foreach ($purchaseTypes as $type)
                                                <div class="checkbox">
                                                    <input type="checkbox" name="purchase_types[]" value="{{ $type->id }}"> {{ $type->name }}
                                                </div>
                                                @endforeach
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-bold btn-pure btn-secondary"
                                                data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-bold btn-pure btn-primary">Simpan</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
        <div class="card-deck row">
            @foreach ($items as $item)
            <div class="col-md-3">
                <div class="card card-shadowed mx-auto rounded">
                    <a href="{{ route('item.show', [$item->store, $item]) }}">
                        <img class="card-img-top h-200px" style="object-fit:cover" src="{{ asset($item::IMAGE_PATH . $item->images()->first()->path) }}"
                            alt="Item image">
                    </a>
                    <div class="card-body">
                        <a href="{{ route('item.show', [$item->store, $item]) }}">
                            <h3 class="card-title b-0 px-0">{{ $item->name }}</h3>
                        </a>
                        <p><b class="text-success">Rp. {{ number_format($item->price) }}</b> /{{ $item->unit_type }}</p>
                        <small><a class="no-border" href="{{ route('store.index', $item->store) }}">{{
                                $item->store->name }}</a></small>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>

    @include('partials.script')
</body>

</html>